module.exports.descriptors = [
    'Aromatic',
    'Buttery',
    'Creamy',
    'Earthy',
    'Flavourful',
    'Golden',
    'Hearty',
    'Intense',
    'Juicy',
    'Lemony',
    'Lovely',
    'Moist',
    'Nutty',
    'Outstanding',
    'Peppery',
    'Regal',
    'Simple',
    'Tasty',
    'Unforgettable',
    'Yummy',
    'Zesty'
]

module.exports.foods = [
    'Apple Turnovers',
    'Veggies',
    'Cabbage',
    'Beef',
    'Chicken',
    'Lamb',
    'Pork',
    'Ice Cream',
    'Cake',
    'Pie',
    'Cookies',
    'Bars',
    'Potatoes',
    'Carrots',
    'Rice',
    'Wings',
    'Brownies',
    'Soup'
]